# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e6e9fa52b45107970404831c721a616fab9692da35d8d6d1203e3b3db6e6966eaa7b7821f0da5a6f746f7af16c7548e2499d888ff4386c728576ce60dd1342

test:
  secret_key_base: a897d01324a1d443f6396c4e087a463a0cb74f7d8308c94f6ab3a10c354dc9494b46acc689e0036f3c36c0ec72ba55c2c1cdc8bf8d57d81e91d6d3353bfe60e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
